name: Hourly anomaly run (commit outputs)

on:
  schedule:
    - cron: '0 * * * *'   # cada hora en minuto 0 (ajusta: '*/30 * * * *' = cada 30m)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run detection
        run: |
          python run_detection.py

      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add outputs || echo "no outputs"
          git commit -m "Update outputs [ci skip]" || echo "no changes to commit"
          git push
